<?php

namespace TestBundle\Repository;
use TestBundle\Entity\PlacementTest;
use TestBundle\Repository\PlacementTestRepository;
use Doctrine\ORM\EntityRepository;

/**
 * PlacementTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacementTestRepository extends EntityRepository
{
        public function addTest(\TestBundle\Entity\PlacementTest $test){
        try{
            $em = $this->getEntityManager();
            $em->persist($test);
            $em->flush();
        }
        catch (\Exception $e){
            throw $e;
        }
    }
}