<?php

namespace TestBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * RespuestasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestasRepository extends EntityRepository
{
}
