test_homepage:
    path:     /test/
    defaults: { _controller: TestBundle:Default:index }
test_nivel:
    pattern: /test/nivel/
    defaults: { _controller: TestBundle:Default:nivel }
test_fin:
    pattern: /test/fin/
    defaults: { _controller: TestBundle:Default:nivel }    
