USE move;

/* Preguntas Nivel Elemental */
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (13,2,'13. I haven\'t got ..... ',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (14,2,'14. ..... orange juice in the glass.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (15,2,'15. He goes to work.....',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (16,2,'16. Which sentence is correct?',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (17,2,'17. We haven\'t got ..... mineral water.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (18,2,'18.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (19,2,'19.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (20,2,'20. Mark ..... fly to London tomorrow.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (21,2,'21. Jenny lives ..... France.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (22,2,'22. John is the manager, you need to speak to .....',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (23,2,'23. I wanted a purple bike but they only had .....',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (24,2,'24. He ..... breakfast yesterday.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (25,2,'25.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (26,2,'26.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (27,2,'27. I have to go to the bank ..... some money.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (28,2,'28. The room was empty. There ..... there.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (29,2,'29. Which of the following options means “in any place”? I\'ve lost my keys. I can\'t find them .....',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (30,2,'30. We can\'t get there by 3:00 pm. There is ..... time.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (31,2,'31. He arrived ..... Heathrow airport on Friday',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (32,2,'32. ..... is it from Barcelona to Madrid?',0,0);

/* Respuestas Nivel Elemental */
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (49,13,'A. no money.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (50,13,'B. lot of money.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (51,13,'C. any money.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (52,13,'D. some money.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (53,14,'A. There isn\'t no',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (54,14,'B. There is any',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (55,14,'C. There isn\'t any',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (56,14,'D. There aren\'t no',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (57,15,'A. by taxi.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (58,15,'B. on taxi.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (59,15,'C. with taxi.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (60,15,'D. in taxi.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (61,16,'A. He wakes up at 9:00 always',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (62,16,'B. He wakes up at always 9:00',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (63,16,'C. He always wakes up at 9:00',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (64,16,'D. He wakes always up at 9:00',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (65,17,'A. a lot',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (66,17,'B. little',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (67,17,'C. too',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (68,17,'D. much',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (69,18,'A. Where playing Manchester United?',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (70,18,'B. Where is playing Manchester United?',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (71,18,'C. Where is Manchester United playing?',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (72,18,'D. Where playing is Manchester United?',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (73,19,'A. What\'s like the weather?',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (74,19,'B. How\'s the weather like?',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (75,19,'C. What\'s the weather like?',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (76,19,'D. How the weather is?',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (77,20,'A. going to',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (78,20,'B. goes to',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (79,20,'C. is going to',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (80,20,'D. go to',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (81,21,'A. at',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (82,21,'B. in',1); 
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (83,21,'C. on',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (84,21,'D. in the',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (85,22,'A. it.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (86,22,'B. him.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (87,22,'C. her.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (88,22,'D. you.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (89,23,'A. a one green.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (90,23,'B. one green.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (91,23,'C. a green one.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (92,23,'D. a green.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (93,24,'A. hadn\'t',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (94,24,'B. no had',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (95,24,'C. didn\'t have got',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (96,24,'D. didn\'t have',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (97,25,'A. Give the Joan money.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (98,25,'B. Give the money to Joan.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (99,25,'C. Give to Joan the money.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (100,25,'D. Give the money at Joan.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (101,26,'A. Mary usually drives carefully.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (102,26,'B. Mary carefully drives usually.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (103,26,'C. Mary carefully usually drives.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (104,26,'D. Mary usually carefully drives.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (105,27,'A. for getting',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (106,27,'B. to get',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (107,27,'C. to getting',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (108,27,'D. for to get',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (109,28,'A. wasn\'t nobody',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (110,28,'B. was anybody',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (111,28,'C. was nobody',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (112,28,'D. was somebody',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (114,29,'A. anywhere.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (115,29,'B. nowhere.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (116,29,'C. nothing.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (117,29,'D. somewhere.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (118,30,'A. few',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (119,30,'B. too little',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (120,30,'C. a few',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (121,30,'D. too few',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (122,31,'A. in',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (123,31,'B. at',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (124,31,'C. on',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (125,31,'D. by',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (126,32,'A. How far',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (127,32,'B. How long',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (128,32,'C. How much',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (129,32,'D. How many',0);


COMMIT;
