USE move;


/* Preguntas Nivel Intermedio */
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (48,4,'48. Which of the following options is correct to indicate that an action happened before another action in the past? I invited Mary out for a meal, but unfortunately she ...... dinner.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (49,4,'49. You can meet me ..... you like.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (50,4,'50. I ..... working at night nowadays.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (51,4,'51. I have to catch the 5:00 am train tomorrow, so I ..... go to bed late.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (52,4,'52. She ..... go to the dentist\'s yesterday.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (53,4,'53. That\'s the ..... of my worries, it\'ll never happen.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (54,4,'54. I wouldn\'t mind ..... tonight.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (55,4,'55. The man ..... in the corner is my boss.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (56,4,'56. "Those cases look heavy"  "..... carry one for you?"  "That\'s very nice of you"',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (57,4,'57. Don\'t forget ..... those letters.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (58,4,'58. Where have you put my keys? I clearly remember .... them on the table last night.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (59,4,'59. You look tired. You ..... go to bed.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (60,4,'60. Which of the following options is correct to express that you recall an action happening in the past? That was a great match. I\'ll never forget ..... Rivaldo score that goal.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (61,4,'61. I thought you .....',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (62,4,'62. Which of the following options is correct to express regret about the past? They ..... last night, but I\'m not sure.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (63,4,'63. He wrote the programme ..... , he didn\'t need  anybody\'s help.',0,0); 

/* Respuestas Nivel Intermedio */
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (192,48,'A. has already had',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (193,48,'B. had already had',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (194,48,'C. have already had',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (195,48,'D. already had',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (196,49,'A. whenever',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (197,49,'B. soon',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (198,49,'C. always',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (199,49,'D. whatever',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (200,50,'A. used to',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (201,50,'B. used',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (202,50,'C. am used to',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (203,50,'D. would',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (204,51,'A. needn\'t',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (205,51,'B. haven\'t',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (206,51,'C. have to',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (207,51,'D. shouldn’t',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (208,52,'A. must',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (209,52,'B. had to',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (210,52,'C. ought to',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (211,52,'D. should have',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (212,53,'A. fewer',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (213,53,'B. less',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (214,53,'C. last',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (215,53,'D. least',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (216,54,'A. to go out',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (217,54,'B. go out',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (218,54,'C. going out',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (219,54,'D. to going out',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (220,55,'A. whose',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (221,55,'B. sitting',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (222,55,'C. is sitting',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (223,55,'D. sits',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (224,56,'A. Will I',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (225,56,'B. Do I have',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (226,56,'C. Shall I',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (227,56,'D. Do it',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (228,57,'A. to post',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (229,57,'B. posting',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (230,57,'C. to posting',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (231,57,'D. post',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (232,58,'A. to leave',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (233,58,'B. left',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (234,58,'C. did leave',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (235,58,'D. leaving',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (236,59,'A. need',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (237,59,'B. have',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (238,59,'C. should have',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (239,59,'D. should',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (240,60,'A. see',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (241,60,'B. to see',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (242,60,'C. seeing',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (243,60,'D. to seeing',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (244,61,'A. will come to the party.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (245,61,'B. were coming to the party.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (246,61,'C. come to the party.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (247,61,'D. have come to the party.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (248,62,'A. must have come',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (249,62,'B. can´t have come',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (250,62,'C. should have come',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (251,62,'D. may have come',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (252,63,'A. by his own',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (253,63,'B. on his own',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (254,63,'C. on himself',0);

COMMIT;