USE move;

/* Preguntas Nivel Pre-Intermedio */
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (33,3,'33. I haven\'t had lunch with my mother ..... more than a year.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (34,3,'34. There ..... spectators at the match.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (35,3,'35. The kitchen can\'t be dirty he .....',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (36,3,'36. I’m looking forward …. from you.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (37,3,'37. Don\'t start .....',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (38,3,'38. He works at the theatre, ..... ?',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (39,3,'39. Simon ..... in Madrid since 1982.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (40,3,'40.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (41,3,'41. Mr. Brown hasn’t arrived .....',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (42,3,'42. Which of the following options is correct to illustrate an improbable situation? If I won the lottery, I ..... a house in the country.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (43,3,'43. Peter is ..... Jane to do it at the moment.',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (44,3,'44. Have you sent that e-mail to Mr. Smyth?',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (45,3,'45. "..... have you been waiting?',0,0);
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (46,3,'46. They weren\'t surprised and nor ..... I.',0,0); 
insert into move.preguntas (id,nivel_id,pregunta,cantidad_ok,cantidad_no_ok) values (47,3,'47. This is the cat ..... I saw.',0,0); 


/* Respuestas Nivel Pre-Intermedio */
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (131,33,'A. since',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (132,33,'B. -----',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (133,33,'C. for',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (134,33,'D. during',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (136,34,'A. were no',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (137,34,'B. weren\'t no',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (138,34,'C. were any',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (139,34,'D. were not',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (140,35,'A. is just clean it.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (141,35,'B. have just cleaned it.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (142,35,'C. just clean it.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (143,35,'D. has just cleaned it.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (144,36,'A. to hear',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (145,36,'B. hearing',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (146,36,'C. hear',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (147,36,'D. to hearing',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (148,37,'A. to shouting!',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (149,37,'B. shouting!',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (150,37,'C. shout!',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (151,37,'D. to shout',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (152,38,'A. doesn\'t he?',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (153,38,'B. does he?',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (154,38,'C. isn\'t he?',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (155,38,'D. didn\'t he?',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (156,39,'A. lives',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (157,39,'B. is living',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (158,39,'C. does live',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (159,39,'D. has lived',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (160,40,'A. I told her what she closed the window.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (161,40,'B. I told her to close the window.',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (162,40,'C. I told she close the window.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (163,40,'D. I told her that she close the window.',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (164,41,'A. already',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (165,41,'B. still',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (166,41,'C. now',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (167,41,'D. yet',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (168,42,'A. would buy',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (169,42,'B. have bought',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (170,42,'C. will buy',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (171,42,'D. would have bought',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (172,43,'A. telling',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (173,43,'B. saying',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (174,43,'C. saying to',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (175,43,'D. telling to',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (176,44,'A. still',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (177,44,'B. already',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (178,44,'C. yet',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (179,44,'D. now',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (180,45,'A. How long',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (181,45,'B. What time',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (182,45,'C. How far',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (183,45,'D. When',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (184,46,'A. weren\'t',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (185,46,'B. wasn\'t',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (186,46,'C. were',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (187,46,'D. was',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (188,47,'A. whom',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (189,47,'B. -----',1);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (190,47,'C. what',0);
insert into move.respuestas (id,pregunta_id,respuesta,correcta) values (191,47,'D. who',0);

COMMIT;